Add EIS burn severity data
NASA-IMPACT/veda-data-pipelines pull request #213
Opened 2022-10-25 17:17 UTC by ividito

Closes #206 

Adds one collection with 5 static assets (annual from 2016-2020)

2022-10-25 18:24 UTC, moradology commented on data/step_function_inputs/mtbs-burn-severity.json
> +    "cogify": "true"
Shouldn't be necessary here, I think. These are already cogs

2022-10-25 21:01 UTC, anayeaye commented on data/collections/mtbs-burn-severity.json
> +                    "2016-01-01",
yeah I think so: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#temporal-extent-object
`[["2016-01-01T00:00:00Z", "2020-12-31T23:59:59Z"]]`

2022-10-27 15:44 UTC, moradology requested changes

2022-10-27 15:44 UTC, moradology commented on data/step_function_inputs/mtbs-burn-severity.json
> +        "filename_regex": "2017.cog.tif",
Looks to me like this cog name might be a bit off. Compare `mtbs_CONUS_2016.cog.tif` vs `2017.cog.tif`

2022-10-27 15:47 UTC, anayeaye commented
@ividito the metadata ingested to the dev stack looks good to me but is there a newer version of the step function input json than what is checked in to this PR? It doesn't look like it would have captured the 2020 COG. Other than that this looks good. I'll 👍  after that update

2022-10-28 18:22 UTC, ividito commented
> @ividito the metadata ingested to the dev stack looks good to me but is there a newer version of the step function input json than what is checked in to this PR? It doesn't look like it would have captured the 2020 COG. Other than that this looks good. I'll 👍 after that update

No newer version, but I think there might still be data from the initial ingestion with the broad regex instead of the entry-per-file. I've updated the PR with a fix.

2022-10-31 17:29 UTC, anayeaye commented
> > @ividito the metadata ingested to the dev stack looks good to me but is there a newer version of the step function input json than what is checked in to this PR? It doesn't look like it would have captured the 2020 COG. Other than that this looks good. I'll 👍 after that update
> 
> No newer version, but I think there might still be data from the initial ingestion with the broad regex instead of the entry-per-file. I've updated the PR with a fix.

The updated version looks good to me

2022-10-31 17:29 UTC, anayeaye approved these changes

2022-11-03 17:37 UTC, ividito commented
@gmarichalgxc @Catalina-Moller @mmaniceraGXC this dataset has been deployed, and the explore view of the new dataset needs to be tested. Deploy preview: https://deploy-preview-127--visex.netlify.app/eis/datasets/mtbs-burn-severity

2022-11-22 15:31 UTC, slesaad commented on data/collections/mtbs-burn-severity.json
> +}
newline

2022-11-28 19:14 UTC, slesaad approved these changes

2022-11-28 21:26 UTC, merged